import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/Layout";
import Hero from "@/sections/Hero";
import AboutUs from "@/sections/AboutUs";

export default function Home() {
	return (
		<>
			<Head>
				<title>CGR Consulting</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<Layout>
				<main className=''>
					<Hero />
					<AboutUs />
				</main>
			</Layout>
		</>
	);
}
